apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cloudevents-spring-boot
spec:
  template:
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          # Uncomment this to send events somewhere.
          # env:
          # - name: K_SINK
          #   value: http://default-broker.default.svc.cluster.local
